I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script
    image n_sad = n_dissapointed.png
  File "game/script.rpy", line 17, in <module>
    image n_sad = n_dissapointed.png
NameError: name 'n_dissapointed' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script
    image n_sad = n_dissapointed.png
  File "C:\Users\puakh\OneDrive\Desktop\renpy-7.1.3-sdk\renpy\ast.py", line 980, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\puakh\OneDrive\Desktop\renpy-7.1.3-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 17, in <module>
    image n_sad = n_dissapointed.png
NameError: name 'n_dissapointed' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
JCS OTOME GAME! 1.0
Sat Jul 20 23:52:39 2019
